# script to load all necessary libraries

library(ncdf4)
library(RCurl)
library(magrittr)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(ggnewscale)
library(cowplot)
library(grid)
library(sp)
library(rgeos)
library(rgdal)
library(sf)
library(xtable)
library(zoo)
library(nest)
library(vegan)
library(readxl)
library(doParallel)
